//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdenCompra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public int Id { get; set; }
        public string Ascode { get; set; }
        public string Description { get; set; }
        public string Size { get; set; }
        public string Model { get; set; }
        public Nullable<int> Mark { get; set; }
        public Nullable<decimal> InventoryStock { get; set; }
        public Nullable<decimal> QuantityTraffic { get; set; }
        public Nullable<decimal> QuantityFactory { get; set; }
        public Nullable<decimal> QuantityAduana { get; set; }
        public Nullable<decimal> QuantityMaxPerContainer { get; set; }
        public Nullable<decimal> QuantityMinStock { get; set; }
        public System.DateTime AddedDate { get; set; }
        public int AddedBy { get; set; }
    }
}
