//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdenCompra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryHistory
    {
        public int Id { get; set; }
        public int ArticleId { get; set; }
        public decimal QuantityAvailable { get; set; }
        public System.DateTime Date { get; set; }
    }
}
