//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdenCompra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPurchaseContainer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderPurchaseContainer()
        {
            this.OrderPurchaseArticlesContainers = new HashSet<OrderPurchaseArticlesContainer>();
        }
    
        public int Id { get; set; }
        public int OrderPurchaseId { get; set; }
        public Nullable<System.DateTime> ManufacturingDate { get; set; }
        public int StatusId { get; set; }
        public decimal MaxCapacityQuantity { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ShippingCompanyId { get; set; }
        public string BL { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public int SortIndex { get; set; }
        public string Situation { get; set; }
    
        public virtual OrderPurchase OrderPurchase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPurchaseArticlesContainer> OrderPurchaseArticlesContainers { get; set; }
    }
}
