//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdenCompra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPurchaseHistory
    {
        public int Id { get; set; }
        public int ArticleId { get; set; }
        public int OrderPurchaseId { get; set; }
        public decimal Quantity { get; set; }
        public string Status { get; set; }
    
        public virtual OrderPurchase OrderPurchase { get; set; }
    }
}
