//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdenCompra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPurchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderPurchase()
        {
            this.OrderPurchaseContainers = new HashSet<OrderPurchaseContainer>();
            this.OrderPurchaseArticlesContainers = new HashSet<OrderPurchaseArticlesContainer>();
            this.OrderPurchaseDelivers = new HashSet<OrderPurchaseDeliver>();
            this.OrderPurchaseHistories = new HashSet<OrderPurchaseHistory>();
        }
    
        public int Id { get; set; }
        public int OrderPurchaseId { get; set; }
        public int ProviderId { get; set; }
        public Nullable<System.DateTime> DateDMA { get; set; }
        public Nullable<System.DateTime> DateRequest { get; set; }
        public Nullable<int> Status { get; set; }
        public string Observation { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPurchaseContainer> OrderPurchaseContainers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPurchaseArticlesContainer> OrderPurchaseArticlesContainers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPurchaseDeliver> OrderPurchaseDelivers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPurchaseHistory> OrderPurchaseHistories { get; set; }
    }
}
