//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdenCompra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Provider()
        {
            this.OrderPurchases = new HashSet<OrderPurchase>();
        }
    
        public int ProviderCode { get; set; }
        public string ProviderName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> OrdersOpened { get; set; }
        public Nullable<int> OrdersProduction { get; set; }
        public Nullable<int> OrdersTransit { get; set; }
        public Nullable<int> OrdersOnPort { get; set; }
        public Nullable<int> OrdersClosed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPurchase> OrderPurchases { get; set; }
    }
}
