//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioCentroServicios.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationCenter
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public System.DateTime SentDate { get; set; }
        public bool Active { get; set; }
        public Nullable<int> OrderPurchaseId { get; set; }
        public Nullable<int> ArticleId { get; set; }
        public string Condition { get; set; }
        public Nullable<System.DateTime> DeactivatedDate { get; set; }
        public Nullable<int> DeactivatedBy { get; set; }
    
        public virtual OrderPurchase OrderPurchase { get; set; }
        public virtual Article Article { get; set; }
    }
}
